[package]
name = "innotrade-contractor"
version = "0.0.1"
repository = "https://github.com/innotrade-platform/innotrade-contractor/"
publish = false

[workspace]
members = ["app", "client", "server"]
