[package]
name = "isomorphic-app"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
virtual-dom-rs = { path = "../percy/crates/virtual-dom-rs" }
css-rs-macro = { path = "../percy/crates/css-rs-macro" }
router-rs = { path = "../percy/crates/router-rs" }
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
wasm-bindgen = { version = "0.2.33", features = ["serde-serialize"] }
js-sys = "0.3"
futures = "0.1.25"
wasm-bindgen-futures = "0.3.14"

[dependencies.web-sys]
version = "0.3"
features = [
    "Event",
    'Headers',
    "HtmlInputElement",
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window'
]

[profile.release]
lto = true
